/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.language.perl.module.template;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.language.perl.utilities.PerlConstants;
import static org.language.perl.utilities.PerlUtilities.disableUpFolderButton;
import org.netbeans.api.project.Project;

public final class PerlModuleTemplateVisualPanel1 extends JPanel {

    /**
     * Creates new form PerlModuleTemplateVisualPanel1
     */
    static String TITLE = "MyTitle";
    static String LOCATION = "MyLocations";
    public Project project;

    public PerlModuleTemplateVisualPanel1(Project p) {
        initComponents();

        this.project = p;

        jLabel1.setText("File name");
        jLabel2.setText("Folder");
        jLabel3.setText("Project Location");
        jLabel4.setText("Created file");

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText(p.getProjectDirectory().getPath());
        jTextField4.setText(p.getProjectDirectory().getPath()
                + PerlConstants.FILE_SEPARATOR);

        jTextField3.setEditable(false);
        jTextField4.setEditable(false);

        jTextField1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
                autoUpdate();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                autoUpdate();
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                autoUpdate();
            }

            public void autoUpdate() {
                jTextField4.setText(jTextField2.getText() + File.separator + jTextField1.getText());
                TITLE = jTextField1.getText();
                LOCATION = jTextField2.getText();
                //LOCATION = jTextField2.getText().replace(PerlConstants.PATH_SEPARATOR, PerlConstants.MODULE_SEPARATOR);
            }
        });

        jTextField2.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
                autoUpdate();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                autoUpdate();
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                autoUpdate();
            }

            public void autoUpdate() {
                jTextField4.setText(jTextField2.getText() + File.separator + jTextField1.getText());
                TITLE = jTextField1.getText();
                LOCATION = jTextField2.getText();
                //LOCATION = jTextField2.getText().replace(PerlConstants.PATH_SEPARATOR, PerlConstants.MODULE_SEPARATOR);
            }
        });

    }

    @Override
    public String getName() {
        return "New Perl Module";
    }

    public String getFilename() {
        return jTextField1.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PerlModuleTemplateVisualPanel1.class, "PerlModuleTemplateVisualPanel1.jLabel1.text")); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(PerlModuleTemplateVisualPanel1.class, "PerlModuleTemplateVisualPanel1.jTextField1.text")); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(PerlModuleTemplateVisualPanel1.class, "PerlModuleTemplateVisualPanel1.jLabel2.text")); // NOI18N

        jTextField2.setText(org.openide.util.NbBundle.getMessage(PerlModuleTemplateVisualPanel1.class, "PerlModuleTemplateVisualPanel1.jTextField2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(PerlModuleTemplateVisualPanel1.class, "PerlModuleTemplateVisualPanel1.jLabel3.text")); // NOI18N

        jTextField3.setText(org.openide.util.NbBundle.getMessage(PerlModuleTemplateVisualPanel1.class, "PerlModuleTemplateVisualPanel1.jTextField3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(PerlModuleTemplateVisualPanel1.class, "PerlModuleTemplateVisualPanel1.jLabel4.text")); // NOI18N

        jTextField4.setText(org.openide.util.NbBundle.getMessage(PerlModuleTemplateVisualPanel1.class, "PerlModuleTemplateVisualPanel1.jTextField4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(PerlModuleTemplateVisualPanel1.class, "PerlModuleTemplateVisualPanel1.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(174, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        PerlModuleTemplateDialog dialog = new PerlModuleTemplateDialog(new javax.swing.JFrame(), true);
        dialog.setVisible(true);

//        PerlModuleFolderSelector folderSelector = new PerlModuleFolderSelector();
//        folderSelector.setTitle("My First Swing Application");
//        folderSelector.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        folderSelector.pack();
//        folderSelector.setAlwaysOnTop(true);
//        folderSelector.setVisible(true);

        /*
         File currentFile = new File(this.getFilename());
         File projectPath = new File(this.project.getProjectDirectory().getPath());

         final JFileChooser fc = new JFileChooser();
         fc.setCurrentDirectory(projectPath);
         fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
         disableUpFolderButton(fc);
         int returnVal = fc.showOpenDialog(this);
         if (returnVal == JFileChooser.APPROVE_OPTION) {
         File file = fc.getSelectedFile();
         //This is where a real application would open the file.
         jTextField2.setText(file.getPath());
         }
         */

    }//GEN-LAST:event_jButton1ActionPerformed


    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
