/*
 * The MIT License
 *
 * Copyright 2024 Sudeep.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.language.perl.statusbar;

import java.io.IOException;
import org.language.perl.utilities.CheckInstalledPerlModules;
import org.netbeans.api.options.OptionsDisplayer;
import org.openide.util.Exceptions;

/**
 *
 * @author Sudeep
 */
public class PerlStatusBarPanel extends javax.swing.JPanel {

    /**
     * Creates new form PerlStatusBarPanel
     */
    private static final long serialVersionUID = 1L;

    public PerlStatusBarPanel() {
        initComponents();
        CheckInstalledPerlModules checkModules = new CheckInstalledPerlModules();
        String platformCompiler = "Perl";
        try {
            statusLabel.setText(platformCompiler + " " + checkModules.getCurrentPerlVersion());
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
        statusLabel.setToolTipText(platformCompiler);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusLabel = new javax.swing.JLabel();

        statusLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/language/perl/file/perl-file.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(statusLabel, org.openide.util.NbBundle.getMessage(PerlStatusBarPanel.class, "PerlStatusBarPanel.statusLabel.text")); // NOI18N
        statusLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        statusLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statusLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusLabel)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void statusLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusLabelMouseClicked
        // TODO add your handling code here:
        OptionsDisplayer.getDefault().open("PerlOnNetBeans/General");
    }//GEN-LAST:event_statusLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
